services:
  - type: web
    name: fintrack-backend
    env: docker
    dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: fintrack-db
          property: connectionString
    plans:
      - name: free

databases:
  - name: fintrack-db
    databaseName: fintrack
    user: fintrack_user
    plan: free